---
name: update-aqua-checksums

on:
  workflow_call:
    inputs:
      aqua_policy_config:
        required: false
        type: string
      aqua_version:
        required: true
        type: string
      policy_allow:
        required: false
        type: string
      working_directory:
        required: false
        default: ""
        type: string
      prune:
        required: false
        default: false
        type: boolean
      ref:
        required: false
        type: string
      runs-on:
        required: false
        type: string
        default: '"ubuntu-latest"'
        description: |
          JSON string for runs-on.
          e.g.
          runs-on: '"macos-latest"'
          runs-on: '["foo"]'
      gh_app_repositories:
        required: false
        type: string
        default: ""
    secrets:
      gh_token:
        required: false
      gh_app_id:
        required: false
      gh_app_private_key:
        required: false

env:
  AQUA_POLICY_CONFIG: ${{inputs.aqua_policy_config}}
  AQUA_LOG_COLOR: always

permissions: {}

jobs:
  update-aqua-checksums:
    # Update aqua-checksums.json and push a commit
    timeout-minutes: 30
    runs-on: ${{fromJSON(inputs.runs-on)}}
    permissions:
      contents: read # To checkout private repository
    steps:
      - name: Get ref
        id: ref
        run: |
          set -eu
          ref=""
          case "$GITHUB_EVENT_NAME" in
            pull_request | pull_request_* )
              ref=$HEAD_SHA
              ;;
          esac
          if [ -n "$INPUT_REF" ]; then
            ref="$INPUT_REF"
          fi
          echo "ref=$ref" >> "$GITHUB_OUTPUT"
        env:
          HEAD_SHA: ${{github.event.pull_request.head.sha}}
          INPUT_REF: ${{inputs.ref}}

      - name: Generate token
        id: generate_token
        if: "! github.event.pull_request.head.repo.fork"
        uses: suzuki-shunsuke/github-token-action@350d7506222e3a0016491abe85b5c4dd475b67d1 # v0.2.1
        with:
          github_token: ${{secrets.gh_token}}
          github_app_id: ${{secrets.gh_app_id}}
          github_app_private_key: ${{secrets.gh_app_private_key}}
          github_app_permissions: >-
            {
              "contents": "write"
            }
          github_app_repositories: ${{inputs.gh_app_repositories}}

      - name: Get skip_push
        id: skip_push
        run: |
          set -eu
          skip_push=""
          case "$GITHUB_EVENT_NAME" in
            pull_request | pull_request_* ) skip_push="${{github.event.pull_request.head.repo.fork}}";;
          esac
          if [ -z "$skip_push" ]; then
            skip_push=false
          fi
          if [ "$TOKEN_TYPE" = "empty" ]; then
            skip_push=false
          fi
          echo "skip_push=$skip_push" >> "$GITHUB_OUTPUT"
        env:
          TOKEN_TYPE: ${{steps.generate_token.outputs.token_type}}

      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{steps.ref.outputs.ref}}
          persist-credentials: false

      - uses: aquaproj/aqua-installer@ea518c135a02fc11ff8024364510c181a5c6b342 # v4.0.3
        if: steps.generate_token.outputs.token_type == 'empty'
        with:
          aqua_version: ${{inputs.aqua_version}}
          policy_allow: ${{inputs.policy_allow}}
          working_directory: ${{inputs.working_directory}}
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}

      - uses: aquaproj/aqua-installer@ea518c135a02fc11ff8024364510c181a5c6b342 # v4.0.3
        if: "steps.generate_token.outputs.token_type != 'empty'"
        with:
          aqua_version: ${{inputs.aqua_version}}
          policy_allow: ${{inputs.policy_allow}}
          working_directory: ${{inputs.working_directory}}
        env:
          AQUA_GITHUB_TOKEN: ${{steps.generate_token.outputs.token}}

      - uses: aquaproj/update-checksum-action@c5df5a5c2a897a9b807068f062140506d092e7ac # v0.2.7
        with:
          skip_push: ${{steps.skip_push.outputs.skip_push}}
          prune: ${{inputs.prune}}
          working_directory: ${{inputs.working_directory}}
        env:
          # To trigger GitHub Actions Workflow by pushing a commit, GitHub App token is required.
          # github.token doesn't trigger GitHub Actions Workflow.
          # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
          # > When you use the repository's GITHUB_TOKEN to perform tasks, events triggered by the GITHUB_TOKEN, with the exception of workflow_dispatch and repository_dispatch, will not create a new workflow run.
          GITHUB_TOKEN: ${{steps.generate_token.outputs.token}}
